# Generated by Django 6.0.2 on 2026-02-24 07:33

from django.db import migrations
import uuid

def create_default_teams(apps, schema_editor):
    Organization = apps.get_model('organizations', 'Organization')
    Team = apps.get_model('organizations', 'Team')
    OrganizationMember = apps.get_model('organizations', 'OrganizationMember')
    
    for org in Organization.objects.all():
        team, created = Team.objects.get_or_create(
            name='General',
            organization=org,
            defaults={'id': uuid.uuid4()}
        )
        # Assign this team to all members of this organization currently missing a team
        OrganizationMember.objects.filter(organization=org, team__isnull=True).update(team=team)

def reverse_teams(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_team_organizationmember_team'),
    ]

    operations = [
        migrations.RunPython(create_default_teams, reverse_teams),
    ]
