# Generated by Django 6.0.2 on 2026-02-24 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_auto_20260224_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmember',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.team'),
        ),
    ]
