# Generated by Django 6.0.2 on 2026-02-25 04:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organizationmember_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_role', models.IntegerField(choices=[(4, 'Admin'), (3, 'Manager'), (2, 'Project Manager'), (1, 'Member')], help_text='The role level the user wants to be temporarily elevated to.')),
                ('target_scope', models.CharField(blank=True, default='organization', help_text="Scope of escalation, e.g. 'organization', 'project:<id>'", max_length=255)),
                ('requested_action', models.CharField(blank=True, default='', help_text='Description of why the escalation is needed.', max_length=255)),
                ('start_time', models.DateTimeField(help_text='When the elevated permission becomes active.')),
                ('end_time', models.DateTimeField(help_text='When the elevated permission expires.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_permission_requests', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to='organizations.organization')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
