# Generated by Django 6.0.2 on 2026-02-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_REASSIGNED', 'Task Reassigned'), ('STATUS_CHANGED', 'Status Changed'), ('ORG_CREATED', 'Organization Created'), ('PROJECT_CREATED', 'Project Created'), ('TASK_CREATED', 'Task Created'), ('MEMBER_ADDED', 'Member Added')], max_length=50),
        ),
    ]
