# Generated by Django 6.0.2 on 2026-02-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('TASK_ASSIGNED', 'Task Assigned'), ('TASK_REASSIGNED', 'Task Reassigned'), ('STATUS_CHANGED', 'Status Changed'), ('ORG_CREATED', 'Organization Created'), ('PROJECT_CREATED', 'Project Created'), ('TASK_CREATED', 'Task Created'), ('MEMBER_ADDED', 'Member Added'), ('TEAM_CREATED', 'Team Created'), ('PERM_ESCALATION_REQUESTED', 'Permission Escalation Requested'), ('PERM_ESCALATION_APPROVED', 'Permission Escalation Approved'), ('PERM_ESCALATION_REJECTED', 'Permission Escalation Rejected'), ('PERM_ESCALATION_EXPIRED', 'Permission Escalation Expired')], max_length=50),
        ),
    ]
